# Generated by Django 2.0.4 on 2019-04-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190425_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_birth',
            field=models.DateField(default='2019-01-01', verbose_name='Дата рождения'),
            preserve_default=False,
        ),
    ]
