# Generated by Django 2.0.4 on 2019-04-26 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190426_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Гражданин'),
        ),
    ]
