# Generated by Django 2.0.4 on 2019-04-27 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20190426_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Гражданин'),
        ),
    ]
