# Generated by Django 2.0.4 on 2019-05-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0003_auto_20190427_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeals',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/static/appeals/', verbose_name='Прикрепляемый документ'),
        ),
        migrations.AddField(
            model_name='appeals',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/static/appeals/imagination', verbose_name='Изображение'),
        ),
    ]
