# Generated by Django 2.0.4 on 2019-05-01 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20190501_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name': 'Ответ на обращение', 'verbose_name_plural': 'Ответы на обращения'},
        ),
    ]
