# Generated by Django 2.0.4 on 2019-05-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_auto_20190501_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/static/answers/', verbose_name='Прикрепляемый документ'),
        ),
        migrations.AddField(
            model_name='answers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/static/answers/imagination', verbose_name='Изображение'),
        ),
    ]
