# Generated by Django 2.0.4 on 2019-05-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_auto_20190501_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/static/responses/', verbose_name='Прикрепляемый документ'),
        ),
        migrations.AddField(
            model_name='responses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/static/responses/imagination', verbose_name='Изображение'),
        ),
    ]
